name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from Repo to server
        # for simple command or script, **run** is the goto
        # actions performs some complex stuff which we would need some stepe or script do
        # see market palce for actions
        # for actions that takes in additional config, ***with*** e.g submodules:
        uses: actions/checkout@v4
        with:
          #optional
          show-progress: 'true'

      # not the os you select already contains preinstalled software see: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
      # click each os to see preinstalled software
      # to manually install software type "github action install <app>" in google e.g github action install java
      - name: Install Node Js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm test
